### ISSUE TITLE
Command Not Work

### ISSUE THREAD

**Issue by bindext** [hop09/hpro#2]
Dear i have subscription command not working please check 

python hop.py

**Comment by hop09** [comment]
@bindext sorry for interruption. it will available soon

**Comment by bindext** [comment]
i will wait
please notify me, when you available

**Comment by hop09** [comment]
the issue has been resolved, you can proceed now

**Comment by bindext** [comment]
not working
~/hpro $ python hop.py

 Active session: vgxohmb3ql9ghdsldrpas0zpj
~/hpro $

Stun here not redirect

**Comment by hop09** [comment]
@bindext please copy and paste these commands in termux

cd && rm -rf hpro && git clone https://github.com/hop09/hpro && cd hpro && python hop.py

**Comment by bindext** [comment]
Thanks Brother, Working Now 👍👍👍👍
